import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme } from "@radix-ui/themes";

const vazir = Vazirmatn({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${vazir.variable} antialiased`}>
        <Theme appearance="dark" className={vazir.className}>
          {children}
        </Theme>
      </body>
    </html>
  );
}
